arb-dir: lib/app/core/l10n/arb
output-dir: lib/app/core/l10n/localizations
template-arb-file: app_pt.arb
output-localization-file: app_localizations.dart
nullable-getter: false
synthetic-package: false
